- Software/PC_Application/CustomWidgets/siunitedit.cpp
- Software/PC_Application/Traces/markerwidget.cpp
- Software/PC_Application/Traces/tracewidget.cpp
- Software/PC_Application/VNA/vna.cpp
Hi Jan!
Here are some of my suggestions.
Noticed some invalid conditions which could cause a crash.
Proposed some cosmetic changes. At least on my favourite monitor(s) (1600x1200, 1600x900), can fit all toolbars without maximizing the app. Depends how you like it...
Propose to selectAll() in siunitedit, to keep text visible upon gaining focus.
> Check some invalid conditions

- Software/PC_Application/Generator/signalgenwidget.cpp
- Software/PC_Application/Generator/signalgenwidget.ui
Hi Jan!
I propose more digits in the frequency widget of signal gen.
And a slight modificaiton of ui panel. Just moved title "generator" to the top of the panel.
I am thinking also of changing the frequency input widget to double spin box. Maybe even to show both lineedit and double spin box, so users can change in both of them as they like. What do you think?
Zoran
> SignalGen - more precision digits; ui panel mod.

- Software/PC_Application/Calibration/calibration.cpp
- Software/PC_Application/Calibration/calibration.h
- Software/PC_Application/VNA/vna.cpp
- Software/PC_Application/VNA/vna.h
- Software/PC_Application/preferences.cpp
Sorry for the other one :(  this should be the right pull request. I've gotta' stop working so late!
As you have more experience, please please, check if this includes the other one, plus my tonight's changes. Then kindly reject...
So here is the text again:
Good morning!
Here is my attempt at some of your suggestions. 
- When starting the application and no calibration is in use...
- Displaying the filename in the tooltip...
Well, the simplest option would be to show the same hint as it is now "bla bla 100M - 600M 1000pt", where the "600M" would be also yellow, assuming this is the limit which was crossed. But I don't see that styling parts of the tooltip text is possible. Am I right? Also, this approach is not very obvious for the user, so I'm not quite happy about it. 
So in parallel, …
> Calibration widget handling

- Software/PC_Application/Calibration/calibration.cpp
- Software/PC_Application/Calibration/calibration.h
- Software/PC_Application/VNA/vna.cpp
- Software/PC_Application/preferences.cpp
Hello Jan!
I was playing with calibration and related stuff and I humbly :) propose some improvements:
calibration.cpp/h
- try to remember active cal.file name for later display
- suggest descriptive filename in "save calibration" dialog; created hzToString function to assist here. (I usually like to save my calibrations such as "cable abc, 40M-700M 400points", to distinguish from another cable e.g. "cable_xyz .... same as before". It gets a bit overwhelming if not precisely tracking wich cal file is which.) Anyway, the suggested filename is easy to delete by user, if they don't like it.
vna.cpp
- highlight "calibration" widget in yellow if calibration is not valid or not existing (any better idea?)
- show name of active cal.file if mouse hovered over widget (Couldn't think of a better …
> Calibration save/load, gui cosmetics

- Software/PC_Application/Traces/tracemarker.cpp
- Software/PC_Application/Traces/tracemarker.h
- Software/PC_Application/Traces/tracemarkermodel.cpp
- Software/PC_Application/appwindow.cpp
- Software/PC_Application/appwindow.h
Jan, good morning once again!
I made some changes according to https://github.com/jankae/VNA2/issues/17#issue-758466939
I believe it's ok but I found two crash instances along the way. 
For clarity, I opened one issue, and continued the other:
https://github.com/jankae/VNA2/issues/18#issue-760862785 Corrected. Almost. Still an occasional crash in a very specific situation. I'm stuck. Please check further.
https://github.com/jankae/VNA2/issues/17#issuecomment-742229782 Device gets locked when reference is set to external. I'm pretty sure this did not happen in some early commits because I was playing with it several times. 
Regarding this pull request, it was easy. I changed one combo box check from 'current position' to string literal. It is safer if we change the order of strings …
> Reference clock widgets - consolidation #17

- Software/VNA_embedded/Makefile
This change introduce a way to modify BINPATH
outside makefile when compiling, allowing developer
to choose from where toolchain is coming and at
same time avoiding to pollute upstream.
> make: set BINPATH as fallback when compiling

- Software/PC_Application/main.cpp
When someone wants to launch application without no gui, i.e. when using SCPI server the following command can be used: 
`./LibreVNA --no-gui`
Which ends up as: 
```
0.000: [info] Listening on port 19542
0.018: [debug] Activating mode "Vector Network Analyzer"
0.028: [debug] Updated device list, found 1
0.028: [debug] Trying to connect to any device
0.028: [debug] Attempting to connect to device...
0.035: [info] USB connection established
0.036: [debug] Receive thread started
0.036: [info] Connected to "serial-id"
```
However, it may happen that another scpi server should be open, however, device is not specified. 
`./LibreVNA --no-gui <port2>`
```
0.000: [info] Listening on port <port2>
0.019: [debug] Activating mode "Vector Network Analyzer"
0.027: [debug] Updated device list, found 1 …
```
> gui: exits gracefully

- Software/PC_Application/LibreVNA-GUI.pro
- Software/PC_Application/Util/app_common.h
- Software/PC_Application/about.cpp
- Software/PC_Application/about.h
- Software/PC_Application/aboutdialog.ui
- Software/PC_Application/appwindow.cpp
- Software/PC_Application/appwindow.h
- Software/PC_Application/main.cpp
Greetings @jankae, I would like to improve what we currently have in About section and the way application was handling app version and revision to be able to show it in about. Here are the main points: 
- All methods about QCoreApplication as set{Organization,ApplicationName,ApplicationVersion} I guess can be declared in main.cpp and from there just grab the instance whenever we want to use those variables in project. As happens when we need to set `setApplicationDescription` and within `AboutDialog` class. I guess that probably this can be enhanced in the future if we can create a derivate class from QCoreApplication and move methods `getAppVersion, getAppGitHash` from `AppWindow` class. What are your thoughts? 
- With these changes introduced, I've added app version when app is …
> implement about dialog, refactor app version/hash

- Software/PC_Application/SpectrumAnalyzer/spectrumanalyzer.cpp
- Software/PC_Application/SpectrumAnalyzer/spectrumanalyzer.h
- Software/PC_Application/Traces/traceplot.cpp
- Software/PC_Application/Traces/traceplot.h
- Software/PC_Application/Traces/tracesmithchart.h
- Software/PC_Application/VNA/vna.cpp
- Software/PC_Application/VNA/vna.h
- Software/PC_Application/appwindow.cpp
@jankae, 
The following commit tries to propagate as quickly as possible new plot settings in active mode. This will avoid: 
- Swap between mode in order to refresh
- Update plot portions while paint events are being generated. See example below. 
If there is a better way to handle this, just let me know and I'll be really happy to refactor it. I guess it was an attempt before to achieve this?
> gui: replot active mode when settings plot are updated

- Software/PC_Application/CustomWidgets/tilewidget.cpp
- Software/PC_Application/CustomWidgets/tilewidget.h
- Software/PC_Application/CustomWidgets/tilewidget.ui
The following commit features to set specific plot as full screen
if double clicked event is triggered while mouse is over that
particular plot.
This becomes handy if you are interested in a particular traces over
that plot and want to inspect it in more detail.
To come back and show all four plots, another double clicked event should be trigger. I guess it's pretty intuitive. 
@jankae what do you think?
> gui: set individual plot as full screen when double clicked

- Software/VNA_embedded/Application/Hardware.cpp
- Software/VNA_embedded/Application/Hardware.hpp
When USE_DEBUG_PINS is enabled and debug session is open, their pin initialization makes debug probe to lost session. As these pins are not used, let's disable it by default.
> fw/hardware: disable debug pins

- .github/workflows/Release_tag_stable.yml
- CHANGELOG.md
Hi @jankae 
After a couple of days I come up with some suggestions in a way LibreVNA artifacts are delivered for every push to mainstream and also whenever a new release is coming up. In PR there will be a couple of things that I need to fix before actually being merged to master and I would like to here your thoughts about this. 
So far, artifacts are delivered using same name. But I think that would be great if community can download them and have unique version names along with it. Based on this, I propose to add:
- From `EmbeddedFirmware` to `EmbeddedFirmware-hw-rev-B-v1.1.1-2021-07-07-12-36`
Name includes following meta data:
1. Hardware revision: B
2. Firmware version
3. Year, month, day, hour, minute at which this build was executed
- From `GUI_Windows` to …
> actions: increase granularity in artifacts, automate releases

- Documentation/DeveloperInfo/DigitalBlockdiagram.svg
- Documentation/DeveloperInfo/PowerBlockdiagram.svg
- Documentation/DeveloperInfo/RFBlockdiagram.svg
The block diagrams in the Readme were very difficult to view while using Github's dark theme. See screenshot:
By adding a white background to each block diagram, they can be viewed clearly:
> Add a white background for each Block Diagram

- Software/PC_Application/Traces/traceplot.cpp
I didn't notice that there were some additional filter associated markers, while testing I saw that the description on that type of marker were overlapping with marker rounded market label. This PR fix this bug so that marker description can be seen after marker label.
> gui/plotxy: fix hidden description in filter markers related

- Software/PC_Application/Device/device.cpp
- Software/PC_Application/Device/device.h
- Software/PC_Application/appwindow.cpp
- Software/PC_Application/main.cpp
Whenever meta types are registered, it make sense to have a static method class as close as possible where `Q_DECLARE_METATYPE` is used. 
I can imagine in the future that possible classes may required to do same, hence, would be convinient to called those static method in `main` rather than in `AppWindow` class.
> app/main/device: move metatypes to device

- Software/PC_Application/appwindow.cpp
- Software/PC_Application/main.cpp
Probably we can move it to`main` because, there this doesn´t depend on `AppWindow` instances.
> main/app: move message pattern to main

- Software/PC_Application/appwindow.cpp
**Summary:** 
Currently VNA input and output references values are obtained in a way that it depends on the position at which they were added throughout the combox widget. This means that if this sort is changed, several parts of the code need an update. e.g.
https://github.com/jankae/LibreVNA/blob/6393ae7fc3a842af2d35e41641390941dab41230/Software/PC_Application/appwindow.cpp#L453
Also, the label name of the combox it may change in the future, and this change shouldn´t affect the logic to determine whether which option to send to the device. neither when importing/exporting setup file. e.g.
https://github.com/jankae/LibreVNA/blob/6393ae7fc3a842af2d35e41641390941dab41230/Software/PC_Application/appwindow.cpp#L871
**Suggestions:**
Based on the following, here is a tentative proposal to fix …
> gui: set/get reference type and output regardless combobox index

- Software/PC_Application/Generator/generator.cpp
- Software/PC_Application/SpectrumAnalyzer/spectrumanalyzer.cpp
- Software/PC_Application/VNA/vna.cpp
- Software/PC_Application/appwindow.cpp
- Software/PC_Application/scpi.cpp
- Software/PC_Application/scpi.h
When returning scpi values, there are common options
that are shared between different commands. This
change introduce a way to define those values in a
single place.
Signed-off-by: Kiara Navarro <sophiekovalevsky@fedoraproject.org>
> scpi/app: unify result name

- Software/PC_Application/appwindow.cpp
Instead of enabling multiple times "connect to" by iterating
over device list, let's use a flag that determine when at
least one device was found. In that way, the enabling method
is executed once.
> app: refactor enable connect to

- Software/PC_Application/CustomWidgets/tilewidget.cpp
- Software/PC_Application/CustomWidgets/tilewidget.h
- Software/PC_Application/CustomWidgets/tilewidget.ui
- Software/PC_Application/LibreVNA-GUI.pro
- Software/PC_Application/Traces/polarchartdialog.ui
- Software/PC_Application/Traces/smithchartdialog.ui
- Software/PC_Application/Traces/traceplot.h
- Software/PC_Application/Traces/tracepolar.cpp
- Software/PC_Application/Traces/tracepolar.h
- Software/PC_Application/Traces/tracepolarchart.cpp
- Software/PC_Application/Traces/tracepolarchart.h
- Software/PC_Application/Traces/tracesmithchart.cpp
- Software/PC_Application/Traces/tracesmithchart.h
The following implementation represent `Sii` parameters in a polar chart.
I would like to receive your initial feedback on this. During development I came up with the following thoughts: 
- It's desirable to apply this chart to parameters not equal to `Sii`?
- It seems that some behavior of `TraceSmithChart` can be shared with `TracePolarChart` but I wasn't sure to actually make a base class right away without having your opinion first. The main drawback that I see in inherit Smith and Polar charts from this base class is adding a extra layer of parent class. Having a third layer in this case would be maintainable in the future?
- There is a new funcionality in this chart that can be used on `SmithChart` as well and it's moving horizontal axis. The expected behavior follows:
- When …
> widgets/charts: implement polar diagram

- Software/VNA_embedded/.cproject
Fix some includes paths and other bits missed in the migration to STM32 Cube IDE. This only affects the release configuration. I believe this explains some of the issues here: https://groups.io/g/LibreVNA-support/topic/errors_when_compiling_new/93525599
> Add missing configurations to release

- Software/PC_Application/LibreVNA-GUI/scpi.cpp
Minor correction to SCPI::match() method, where one compare condition is repeated and another omitted. This can result in a false mismatch for a valid command string.
Change should now cover matching of each expected combination of standard and alternate command strings.
> fix duplicate condition in match() string comparisons

- Software/PC_Application/LibreVNA-GUI/Device/firmwareupdatedialog.cpp
- Software/PC_Application/LibreVNA-GUI/LibreVNA-GUI.pro
- Software/VNA_embedded/Application/Communication/PacketConstants.h
- Software/VNA_embedded/Application/Communication/Protocol.cpp
- Software/VNA_embedded/Application/Communication/Protocol.hpp
Issue:
The USB communication protocol uses literals for data structuring and indexing, making the code challenging to understand and maintain. An update to packet structure would require manually locating and interpreting individual literal values with prior knowledge of their significance.
Fix:
This commit introduces a separate header file and namespace, `PacketConstants`, containing named constants to replace field-specific literals. It also standardizes buffer incrementation in `encode()`/`decode()` methods, and reduces some ambiguity with combined packet header length vs distinct header field length.
Constants were created in a separate header file so that they might easily be included in host projects which require the packet structure, without the device protocol …
> replace USB protocol literals with named constants

- Documentation/UserManual/SCPI_Examples/libreVNA.py
- Software/Integrationtests/Integrationtest.py
- Software/Integrationtests/tests/TestBase.py
- Software/Integrationtests/tests/TestCalibration.py
- Software/Integrationtests/tests/TestRST.py
- Software/Integrationtests/tests/TestStatusRegisters.py
- Software/Integrationtests/tests/TestSync.py
- Software/Integrationtests/tests/TestVNASweep.py
libraVNA.cmd() no longer expects blank line responses.  By default, it checks status after each command to match the previous behavior. Check can be disabled by optional cmd() parameter for handling expected failure cases, or by turning off the default flag.
Commands such as *WAI may take longer than anything previously.  Make it possible to override the default time-out in cmd() and query().
Change poll loops in TestCalibration and TestVNASweep to *WAI calls.
Note: Not tested with LibreCAL
> Update integration tests for SCPI improvements

- Software/PC_Application/.gitignore
When working on the LibreVNA-GUI project directly in QT-Creator on Windows the build folder ends up in git changes.
> add LibreVNA-GUI build folder to .git-ignore

- Hardware/Kicad/PowerSupply.kicad_sch
change LM 3370 MPN from LM3370SD-4221 to LM3370SD-3021;
The default output voltage of the LM3370SD-3021 BUCK 1 is 1.2V, which meets the VCCINT voltage requirements of the FPGA chip.
> change LM3370 MPN
